"""empty message

Revision ID: d5e0b09f5f5e
Revises: 3d0756c3424e
Create Date: 2020-05-06 17:25:24.643136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e0b09f5f5e'
down_revision = '3d0756c3424e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
